# DocuSynapse Server Docker Compose
version: '3.8'

services:
  # MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "11434:11434"  # Ollama port
    environment:
      - OLLAMA_HOST=0.0.0.0
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: docuSynapse-server-network
